### ISSUE TITLE
Bug Report: it keeps saying “a problem repeatedly occurred on hadobedo” how do I fix this

### ISSUE THREAD

**Issue by Khaminations** [hadobedo/FunkiniOS#2]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [x] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by hadobedo** [comment]
Are you using the Safari version or IPA version? Also, which device are you using?

**Comment by Khaminations** [comment]
I’m using an iPhone SE safari version

**Comment by hadobedo** [comment]
The safari version only works reliably on devices with 3-4GB of ram, you'll have to install the IPA version to have it run on your device :/
