### ISSUE TITLE
Option to split controls

### ISSUE THREAD

**Issue by thoricelli** [hadobedo/FunkiniOS#4]
Currently the controls are kind of uncomfortable.
With the original game you'd put your hands on the A and S keys together w/ the up and right arrows.

How about an option to split the controls to: 
- left and down to the left side of the screen, 
- up and right on the right side of the screen 
(putting A and B above the right side controls or user chosen)

You'd still have to use your thumbs to play but at least you can hit 2 notes at once.

**Comment by hadobedo** [comment]
I might implement that in a future update along with a 'sectioned' control scheme, i.e 4 quadrants on the screen for left, down, up, right, etc. The way haxe handles virtualpads is kinda crappy but i'll see what i can do
