### ISSUE TITLE
Bug Report: Game Chrashes on a spesifc songs ends.

### ISSUE THREAD

**Issue by Wondermine** [hadobedo/FunkiniOS#6]
### Safari or App
- [] [Safari](https://hadobedo.github.io)
- [X] Standalone IPA

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Play week 4, play until the first song finishes, after the car passes the game crashes, this happens to week 3 sometimes as well.
## Please describe your issue. Provide extensive detail and images if possible.
I feel its something similar with the passing car (week 4) and the passing train (week 3) or something similar with the hair animation for the girlfriend (which is not applied in the port).

week 5 does the same thing, it crashes once the first song finishes.
## IOS AND DEVICE
IOS 14.1, iPhone 6s, Checkra1n jailbreak.

**Comment by hadobedo** [comment]
Week 4 is sorta hard on RAM, especially on older devices & newer iOS versions. Since I couldn't compress the mom assets as the .fla's aren't public and manually resizing would be a nightmare with my current skillset, this isn't really something I can fix rn :(

**Comment by Wondermine** [comment]
Sadly, np man i feel you, anyways, thanks for making a port for ios!
